Gplr 82 aktive reise setzen
Geplatzter-Reifen/foof pull request #20
Opened 2024-11-08 12:20 UTC by SimonJohannesEngelhardt

2024-11-08 13:28 UTC, MarcoCoreDuo requested changes

2024-11-08 13:28 UTC, MarcoCoreDuo commented on model/database_functions.ts
> +  database.write(async () => {
```suggestion
  await database.write(async () => {
```

Ohne awaits werden die Promises nicht aufgelöst.

2024-11-08 13:28 UTC, MarcoCoreDuo commented on model/database_functions.ts
> +    journey.update(() => {
```suggestion
    await journey.update(() => {
```

2024-11-08 13:28 UTC, MarcoCoreDuo commented on model/database_functions.ts
> +  database.write(async () => {
```suggestion
  await database.write(async () => {
```

2024-11-08 13:28 UTC, MarcoCoreDuo commented on model/database_functions.ts
> +    journey.update(() => {
```suggestion
    await journey.update(() => {
```

2024-11-08 13:28 UTC, MarcoCoreDuo commented on model/database_functions.ts
> -};
Ist es nicht übersichtlicher, wenn alle Exports am Ende sind?

2024-11-08 13:57 UTC, SimonJohannesEngelhardt commented on model/database_functions.ts
> -};
Ja, aber man vergisst evtl das man eine neue Funktion noch exportieren muss. Aber ich lasse es dann erstmal so

2024-11-10 16:37 UTC, MarcoCoreDuo approved these changes

2024-11-10 16:38 UTC, merged