Gplr 139 gefahrene route auf der aufzeichnen karte anzeigen
Geplatzter-Reifen/foof pull request #59
Opened 2024-12-03 15:14 UTC by Katzablanka

- [x] Wenn nötig, refactored? (Pfadfinderregel)
- [] Tests ausreichend vorhanden?
- [x] Code ausreichend kommentiert / dokumentiert?
- [ ] Dark-Mode beachtet?
- [x] PR in Discord gepostet?

2024-12-05 15:06 UTC, SimonJohannesEngelhardt commented
Erstmal allgemein, sieht ziemlich cool aus und gefällt mir sehr gut. 
@Fieeesch hat nur angemerkt, dass du den zweiten Punkt (der die Live-Location angibt) nicht brauchst, da sie den dann in ihrer Story macht

2024-12-05 15:55 UTC, SimonJohannesEngelhardt requested changes

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Stage/activeStageWrapper.tsx
> +  // }
Kommentar entfernen bitte

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/StageMapLine.tsx
> +}) => {
```suggestion
type MapLineType = {
locations: Location[];
  stageId: number;
};
const StageMapLine = ({
  locations,
  stageID,
  active,
}: MapLineType) => {
```
Oder so ähnlich, halt den Typen rausziehen

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on app/(tabs)/(home)/index.tsx
> +          setActiveStageId(null);
Du kanst hier nicht null reingeben, wenn du den State typisierst mit `<string>`. Wenn dann müsste es wahrscheinlich `string|null` sein

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on app/(tabs)/(home)/index.tsx
> +            centerCoordinate={[8.24, 50.0826]}
Warum stellst du hier feste Koordinaten ein?

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/StageMapLine.tsx
> +  );
Kann bestimmt weg

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
> +  console.log("stages-------->" + stages);
Unnötiger console.log

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
> +}) => {
Hier auch gerne den typ rausziehen

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
Nit: Dateinamen großschreiben

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/StageMapLine.tsx
Ich hab zwar verstanden was die Komponente macht, aber der Name ist nicht so ganz aussagend finde ich. Hab aber leider gerade auch keine bessere Idee

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
Hier weiß ich leider auch keinen beseren Namen, ist aber von außen nicht ganz klar

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
> +        console.log("the stage id--->" + stage.stage.id);
Unnötiger console.log

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Stage/activeStageWrapper.tsx
Hier gerne auch den Namen groß schreiben

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
> +  );
Warum muss hier nochmal der Access Token sein?

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
> +          console.log("stage title---->" + stage.title);
Unnötiges console.log

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
> +          console.log("stage locations---->" + locations); // Fetch locations for each stage
Console.log weg

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
> +          return { stage, locations };
Kann man das in eine Funktion auslagern die dann etwas besser beschreibt was hier passiert?

2024-12-05 15:55 UTC, SimonJohannesEngelhardt commented on components/Stage/activeStageWrapper.tsx
> +  console.log("locations in stage wrapper -->" + locations);
Console.log weg

2024-12-05 17:23 UTC, MarcoCoreDuo requested changes
Bitte noch alle nicht genutzten imports entfernen.

2024-12-05 17:23 UTC, MarcoCoreDuo commented on app/(tabs)/(home)/index.tsx
> +            animationDuration={2000}
```suggestion
```
Das brauchst du hier nicht mehr. Das habe ich in Zeile 75 verschoben.

2024-12-05 17:23 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +import { Feature, FeatureCollection, LineString, Point } from "geojson";
```suggestion
import type { Feature, FeatureCollection, LineString, Point } from "geojson";
```
Bitte einmal ```npm remove geojson``` machen und ```npx expo install @types/geojson``` ausführen. 
Die geojson libary ist fürs parsen gedacht und schon lange nicht mehr geupdatet worden. Du brauchst hier nur die Types.

2024-12-05 17:23 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +  };
```suggestion
  const collection: FeatureCollection = featureCollection<Point | LineString>([
    stage,
    firstPoint,
    lastPoint,
  ]);
```
Benutz lieber die Library

2024-12-05 17:23 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +      shape={featureCollection}
```suggestion
      shape={collection}
```

2024-12-05 21:11 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +          lineJoin: "round",
```suggestion
          lineJoin: "round",
          belowLayerID="road-label",
          aboveLayerID="routeSource",
```
Damit Straßennamen noch sichtbar sind und die Line über der geplanten Routenlinie liegt.

2024-12-05 21:14 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +          circleStrokeColor: theme["color-primary-500"],
```suggestion
          circleStrokeColor: theme["color-primary-500"],
          aboveLayerID="routeSource",
```

2024-12-05 21:14 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +          circleStrokeColor: theme["color-primary-500"],
```suggestion
          circleStrokeColor: theme["color-primary-500"],
          aboveLayerID="routeSource",
```

2024-12-08 14:18 UTC, MarcoCoreDuo submitted a review, later dismissed
Hab noch paar Dinge gefunden

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +  stageID,
```suggestion
  stageId,
```
Und was ist mit dem active? Du hast keinen Type definiert und übergibst es auch nicht, wo du StageMapLine benutzt.

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +      id={`lineSource-${stageID}`}
```suggestion
      id={`lineSource-${stageId}`}
```

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +        id={`lineLayer-${stageID}`}
```suggestion
        id={`lineLayer-${stageId}`}
```

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +        id={`startPointLayer-${stageID}`}
```suggestion
        id={`startPointLayer-${stageId}`}
```

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +        id={`endPointLayer-${stageID}`}
```suggestion
        id={`endPointLayer-${stageId}`}
```

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/stagesMapView.tsx
> +        maxLevel={15}
```suggestion
        minZoomLevel={5}
        maxZoomLevel={15}
```
minLevel und maxLevel gibt es nicht

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/stagesMapView.tsx
> +            stageID={stage.stage.id}
```suggestion
            stageId={stage.stage.id}
```

2024-12-08 14:18 UTC, MarcoCoreDuo commented on app/(tabs)/(touren)/stagesMapViewWrapper.tsx
> +}
```suggestion
type Params = {
  tourId: string;
};

export default function StagesMapViewWrapper() {
  const { tourId } = useLocalSearchParams<Params>(); // Get tourId from URL
  if (!tourId) {
    return (
      <Layout>
        <Text category="h5" status="danger">
          No tourId provided.
        </Text>
      </Layout>
    );
  }

  // Pass tourId to the enhanced component
  return <StagesMapView tourId={tourId} />;
}
```
Observed StagesMapView hat keinen tour Parameter

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/stagesMapView.tsx
> +}) => {
```suggestion
const StagesMapView = ({
  stages,
}: {
  stages: Stage[];
}) => {
```
tour kann nicht übergeben werden

2024-12-08 14:18 UTC, MarcoCoreDuo commented on components/Tour/stagesMapView.tsx
> +  }, [tour]);
```suggestion
```
Vllt. das erstmal weglassen, weil das nicht so funktioniert

2024-12-08 14:30 UTC, MarcoCoreDuo reviewed
Sorry, hatte das aus versehen im Style platziert

2024-12-08 14:30 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +        style={{
```suggestion
        belowLayerID="road-label"
        aboveLayerID="routeSource"
        style={{
```

2024-12-08 14:30 UTC, MarcoCoreDuo commented on components/Tour/StageMapLine.tsx
> +        filter={["==", "name", "Start"]}
```suggestion
        filter={["==", "name", "Start"]}
        aboveLayerID="routeSource"
```

2024-12-09 15:01 UTC, SimonJohannesEngelhardt commented
Bitte noch die Lint Fehler beheben

2024-12-09 15:02 UTC, SimonJohannesEngelhardt commented on components/Tour/stagesMapView.tsx
Das bitte noch machen

2024-12-09 15:14 UTC, Katzablanka commented
> Bitte noch die Lint Fehler beheben
Hab alles eifern außer 
 80:6  warning  React Hook useEffect has a missing dependency: 'getCurrentLocation'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
Hab keine Ahnung, ist aber auch nicht bei mir geschrieben

2024-12-09 15:38 UTC, SimonJohannesEngelhardt approved these changes

2024-12-09 15:50 UTC, MarcoCoreDuo commented on app/(tabs)/(touren)/_layout.tsx
> +          title: "Map of Stages",
```suggestion
          title: "Etappenübersicht",
```

2024-12-09 19:37 UTC, merged