Gplr 163 testing
Geplatzter-Reifen/foof pull request #61
Opened 2024-12-03 21:20 UTC by SimonJohannesEngelhardt

- [ ] Wenn nötig, refactored? (Pfadfinderregel)
- [ ] Tests ausreichend vorhanden?
- [ ] Code ausreichend kommentiert / dokumentiert?
- [ ] Dark-Mode beachtet?
- [ ] PR in Discord gepostet?

2024-12-12 11:40 UTC, Fieeesch requested changes
Erstmal übel das Biest an PR, richtig gut. Ein paar Sachen noch:

- Ich bekomme beim Ausführen der Tests diese Meldung hier:
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```
Hast du die auch? Ignorieren wir die einfach?

- Außerdem: Ist es Absicht, dass der Test für den SharingService fehlt? Either way, mach den dann am besten im Rahmen deines Refactorings.

- Außerdem: bei manchen Test würden ein paar mehr Testcases nicht schaden. Hab ich dann meistens drangeschrieben. Wenn die aber eher zu dem Refactoring von wem anders gehören, schreib am besten ein //TODO dran. Sonst denkt man "der test existiert schon, ich brauche nichts mehr machen"

2024-12-12 11:40 UTC, Fieeesch commented on services/__tests__/statisticsService-test.ts
> +    });
Noch einen Testcase für Minuten? oder einen existierenden abändern?

2024-12-12 11:40 UTC, Fieeesch commented on services/__tests__/statisticsService-test.ts
schöner Test :)

2024-12-12 11:40 UTC, Fieeesch commented on test-utils/test-utils.tsx
ich denke, hier wären ein paar mehr Kommentare schön. Falls du passende findest

2024-12-12 11:40 UTC, Fieeesch commented on test-utils/test-utils.tsx
> +const AllTheProviders = ({ children, use_dark_theme = true }: Props) => {
use_dark_theme eher default false oder nicht?

2024-12-12 11:40 UTC, Fieeesch commented on utils/locationUtil.ts
> +}
Sehr cool dass du das hinzugefügt hast

2024-12-12 11:40 UTC, Fieeesch commented on utils/colorUtil.ts
bin großer Fan deiner Ergänzungen hier

2024-12-12 11:40 UTC, Fieeesch commented on utils/locationUtil.ts
> +};
Ist es schlau, das Ding hier auch Location zu nennen, wenn wir schon eine DB-Klasse mit dem gleichen Namen haben?

2024-12-17 08:07 UTC, SimonJohannesEngelhardt commented on README.md
Das könnte noch besser werden. Aber fürs erste sollte es reichen

2024-12-17 08:41 UTC, SimonJohannesEngelhardt commented on services/statisticsService.ts
>  // Distance //
Ich verstehe nicht was hier verschoben werden soll

2024-12-17 08:41 UTC, SimonJohannesEngelhardt commented on jest.config.js
> +    "!**/.expo/**",
Was ist das letzte Ding? Der Android Ordner wird doch nicht mal mit committet

2024-12-17 08:42 UTC, SimonJohannesEngelhardt commented on jest-setup.ts
> +}));
Nichts

2024-12-17 08:47 UTC, SimonJohannesEngelhardt commented on README.md
> +   describe("<einzelne Funktion oder Komponente>", () => {
Ja das kann man sich wie ne Ordnerstruktur vorstellen. Dann wird es gut geschachtelt und auch gut angezeigt

2024-12-17 08:48 UTC, SimonJohannesEngelhardt commented on components/Statistics/__tests__/TourStats-test.tsx
> +    const tour = new MockTour();
Hab ein TODO hinzugefügt

2024-12-17 08:49 UTC, SimonJohannesEngelhardt commented on app/(tabs)/(touren)/__tests__/index-test.tsx
> +    expect(view).toMatchSnapshot();
Stimmt, das lasse ich auch als TODO drin

2024-12-17 08:53 UTC, SimonJohannesEngelhardt commented on jest.config.js
> +    "!**/.expo/**",
Ist angepasst

2024-12-17 08:54 UTC, SimonJohannesEngelhardt commented on model/createDatabase.ts
> -const useJsi = Platform.OS === "ios"; // Nicht ganz sicher, ob das nicht auch für alle Plattformen geht
Die wird erstmal nicht gebraucht, da wir vorerst ios nicht unterstützen

2024-12-17 09:49 UTC, Fieeesch approved these changes
Darf jetzt durch. Keep up the good work!

2024-12-17 10:26 UTC, merged