Gplr 183 refactoring testing kommentare marco
Geplatzter-Reifen/foof pull request #72
Opened 2024-12-19 16:16 UTC by MarcoCoreDuo

- [x] Wenn nötig, refactored? (Pfadfinderregel)
- [x] Tests ausreichend vorhanden?
- [x] Code ausreichend kommentiert / dokumentiert?
- [x] Dark-Mode beachtet?
- [x] PR in Discord gepostet?

Ich habe das Routezeug in andere Dateien verschoben, damit die home index bisschen leerer wird. Außerdem habe ich alle utils Dateien von util in utils umbenannt, weil es ja mehrere utils in einer Datei gibt.

2025-01-04 14:34 UTC, Fieeesch requested changes
Gutes Refactoring, man sieht dass du recherchiert hast :)

Ich hab dir paar Sachen aufgeschrieben, wo ich verwirrt war, oder die noch verbessert werden sollten (v.a. Kommentare schreiben). 

Und schau bitte nochmal auf den Coverage Report und teste wenn möglich noch etwas mehr (falls es nicht zu viel Zeit frisst, Test sollten nicht geplante Features verzögern, insbesondere wegen dem Feature Freeze in paar Tagen)

2025-01-04 14:34 UTC, Fieeesch commented on app/(tabs)/(touren)/index.tsx
> +          router.navigate({
Wusste gar nicht dass es das gibt, nice

2025-01-04 14:34 UTC, Fieeesch commented on components/Route/RenderRoute.tsx
Gleiches hier. Ein Kommentar, der die Datei im Ganzen, sowie die einzelnen Teile (Linelayer, Circlelayer, ..) erklärt

2025-01-04 14:34 UTC, Fieeesch commented on components/Statistics/TourStats.tsx
> +  stage,
wofür ist diese einzelne Stage? die wird gar nicht benutzt

2025-01-04 14:34 UTC, Fieeesch commented on components/Statistics/TourStats.tsx
>  // Bridge component that determines which TourStats component to render based on the active stage.
Kannst du noch in nem Kommentar erklären, warum zwei verschiedene braucht und worin sie sich unterscheiden?

2025-01-04 14:34 UTC, Fieeesch commented on database/model/model.ts
> +    routes: { type: "has_many", foreignKey: "stage_id" },
Warum ist die Stage mit Routen assoziiert? Eigentlich ist doch nur die Tour mit Routen assoziiert?

2025-01-04 14:34 UTC, Fieeesch commented on database/model/model.ts
> +  @children("routes") routes;
Nochmal: Warum sollte eine Stage eine Route als Kind haben?

2025-01-04 14:34 UTC, Fieeesch commented on services/data/routeService.ts
Kommentare, mögen wir :D

2025-01-04 14:34 UTC, Fieeesch commented on utils/__tests__/locationUtils-test.ts
> +  describe("calculateBounds", () => {
Wenn es nicht zu viel Aufwand wäre, fände ich Tests mit mehr Punkten, die im Zickzack verbunden sind, sinnvoll. Und ein Test, der schaut, was passiert, wenn das Geojson keine Punkte / keine sinnvollen Daten enthält.

2025-01-04 14:34 UTC, Fieeesch commented on utils/locationUtils.ts
> +export function calculateBounds(geoJson: FeatureCollection): {
Hier fehlt mir Error-Handling. Was ist, wenn die Geojson keine sinnvollen Daten enthält? Oder keine Punkte? Infinity zurückzugeben ist irgendwie nicht so richtig.

2025-01-04 14:34 UTC, Fieeesch commented on utils/locationUtils.ts
> +    sw: [Infinity, Infinity],
Hier vielleicht eher die maximalen Gradzahlen nehmen (180, -180). Dann gibt man bei nicht sinnvollen Geojsons wenigstens gültige koordinatenwerte zurück

2025-01-04 20:43 UTC, MarcoCoreDuo commented on app/(tabs)/(home)/index.tsx
> +          {activeTour && <EnhancedRenderRouteV2 tour={activeTour} />}
Annas StageLine mache ich dann im anderen PR.

2025-01-04 20:46 UTC, MarcoCoreDuo commented on app/(tabs)/(touren)/index.tsx
> +          router.navigate({
Das verhindert, dass ein Screen mehrmals übereinander gepusht wird. Wenn der Screen schon geladen ist, nutzt navigate den Vorhandenen.

2025-01-04 21:05 UTC, MarcoCoreDuo commented on components/Statistics/TourStats.tsx
> +  stage,
Das ist die aktive Stage, die observed wird. Die wird aber nicht benutzt, weil alles immer neu berechnet wird, wenn sich was an der aktiven Stage ändert. Ich könnte den Parameter auch weglassen, aber die stage wird trotzdem immer mit übergeben. Ich dachte nur ich lasse das drin, damit man es nicht vergisst.

2025-01-04 21:16 UTC, MarcoCoreDuo commented on components/Statistics/TourStats.tsx
>  // Bridge component that determines which TourStats component to render based on the active stage.
Die Kommentare, die da schon stehen erklären das eigentlich schon.

```js
// observe the stage (tracks updates to the stage)
const enhance = withObservables(["stage"], ({ stage }: { stage: Stage }) => ({
  stage,
}));
```

```js
// observe stages of a tour (only tracks create and delete in the stages table)
const enhanceV2 = withObservables(["tour"], ({ tour }: { tour: Tour }) => {
  return {
    tour,
    stages: tour.stages,
  };
});
```

2025-01-04 21:21 UTC, MarcoCoreDuo commented on database/model/model.ts
> +    routes: { type: "has_many", foreignKey: "stage_id" },
Ein Eintrag in der Routen Tabelle kann auch eine stageid haben, weil wir mal gesagt hatten, dass man auch eine Route für eine Etappe planen kann. Ich habe hier nur fehlende Referenzen ergänzt. Die Datenbank ist unverändert.

2025-01-04 21:58 UTC, MarcoCoreDuo commented on utils/locationUtils.ts
> +export function calculateBounds(geoJson: FeatureCollection): {
Wenn Bounds am Ende noch Infinity enthält schmeißt es jetzt einen Fehler.

2025-01-05 10:33 UTC, Fieeesch requested changes
Eine winzige Änderung noch :')

2025-01-05 10:33 UTC, Fieeesch commented on utils/locationUtils.ts
> +    if (coord.length === 2) {
Zeile 90 und 91 sollten doch eher vertauscht sein, oder?

2025-01-05 11:05 UTC, Fieeesch approved these changes
Alles klar, kann jetzt durch

2025-01-05 11:06 UTC, merged