Gplr 105 start und ziel von manuellen etappen auf der karte suchen
Geplatzter-Reifen/foof pull request #76
Opened 2024-12-30 20:46 UTC by MarcoCoreDuo

- [x] Wenn nötig, refactored? (Pfadfinderregel)
- [x] Tests ausreichend vorhanden?
- [x] Code ausreichend kommentiert / dokumentiert?
- [x] Dark-Mode beachtet?
- [ ] PR in Discord gepostet?

Man kann jetzt zwei Marker auf einer Karte platzieren und zwischen diesen switchen. Wenn man dann auf Erstellen klickt, bekommt man ein Modal zum Eingeben von Start- und Endzeit. Außerdem werden Koordinaten und Datum/Uhrzeit zwischen den Komponenten geteilt. Es wird auch die Kameraposition der Karte gespeichert, sodass man wieder an derselben Stelle landet, wenn man den ButtonSwitch benutzt.

Ich habe außerdem ein paar Komponenten von Anna modularer gemacht, damit ich sie auch bei mir einsetzen konnte.

Tests sind für alle Komponenten, die nicht MapView benutzen, vorhanden.

2025-01-04 15:41 UTC, Fieeesch requested changes
Erstmal, ich liebe den Kommentar den du zu dem PR geschrieben hast, der fasst alles echt gut zusammen und gibt einen easy Einstieg! Und ich find die Story hast du sehr gut umgesetzt.

Mir ist aber ein Bug bei der Synchronisierung der Zeit aufgefallen: Wenn ich die Zeit (egal ob Start oder Ende) im Linken Tab auswähle, wird sie nicht direkt im Button aktualisiert, sondern erst nachdem ich einmal kurz den Tab gewechselt habe. Und wenn ich danach im rechten Tab auf Erstellen klicke, steht da nicht die richtige Uhrzeit. Die Etappe wird dann aber trotzdem mit den gewählten Zeiten erstellt, es ist also nur ein Anzeigefehler. Ich glaube es liegt daran, dass du useRef statt useState verwendest. Bei useState wird nämlich neu gerendert, bei useRef nicht.

Ansonsten brauchst du auf jeden Fall noch mehr Kommentare.

2025-01-04 15:41 UTC, Fieeesch commented on app/(tabs)/(touren)/createManualStage.tsx
> +  const setCoordinate = (coordinate: Position) => {
Kommentar!

2025-01-04 15:41 UTC, Fieeesch commented on app/(tabs)/(touren)/createManualStage.tsx
> +  const handleCreateButton = async () => {
Kommentar!

2025-01-04 15:41 UTC, Fieeesch commented on app/(tabs)/(touren)/createManualStage.tsx
> +  const renderStartCoordinateInput = (
Kommentar!

2025-01-04 15:41 UTC, Fieeesch commented on app/(tabs)/(touren)/createManualStage.tsx
> +  const handleMapIdle = (state: MapState) => {
Kommentar!

2025-01-04 15:41 UTC, Fieeesch commented on components/Map/Marker.tsx
> +        <Icon name="location-dot" size={30} color="black" />
Bitte auf eine Farbe aus dem Theme zurückgreifen. Ich schlage color-basic-600 vor, die ist in beiden themes gleich und ein dunkles Grau. Das bringt besser rüber, dass dieser Marker jetzt deaktiviert ist.

2025-01-04 15:41 UTC, Fieeesch commented on components/Map/Marker.tsx
> +    <MapboxGL.PointAnnotation
Kannst du hier einen Kommentar hinzufügen, der die einzelnen Parameter der PointAnnotation erklärt?

2025-01-04 15:41 UTC, Fieeesch commented on components/Map/MapWithMarkers.tsx
> +  const setCoordinate = (index: number, coordinates: Position) => {
Hier im Kommentar insbesondere darauf eingehen, wann die jeweilige Methode gecallt wird (handleMapPress beim klick auf die Karte, setCoordinate z.b. beim Draggen des Markers wenn ich das richtig verstanden habe). Ich hab nämlich beim ersten Mal lesen gedacht, das hier ist redundanter Code.

2025-01-04 15:41 UTC, Fieeesch commented on components/Map/MapWithMarkers.tsx
> +  const handleMapPress = (feature: Feature) => {
Kommentar

2025-01-04 15:41 UTC, Fieeesch commented on components/Map/MapWithMarkers.tsx
> +  const [startMarkerCoordinate, setStartMarkerCoordinate] =
Kommentar hierfür und für endMarkerCoordinate (kann beides in einem Kommentar sein)

2025-01-04 15:41 UTC, Fieeesch commented on components/Map/MapWithMarkers.tsx
> +    <Layout style={styles.container}>
Füge hier bitte für die einzelnen Elemente Kommentare hinzu. Wie das aussehen kann, kannst du in (home)/index oder (tour)/index sehen

2025-01-04 15:41 UTC, Fieeesch commented on components/Modal/DateTimeButton.tsx
Auslagern und wiederverwenden, sehr cool!

2025-01-04 15:41 UTC, Fieeesch commented on components/Modal/DateTimeButton.tsx
> +          : date.toLocaleTimeString()}
Hier sind leider Sekunden mit drin, das irritiert (ist zwar nicht von dir so gemacht, aber ist mir aufgefallen und vllt kannst du es grad ändern). Du kannst stattdessen die DateUtils zum formatieren benutzen.

2025-01-04 15:41 UTC, Fieeesch commented on components/Modal/__tests__/DateTimeButton-test.tsx
Hier vielleicht noch einen Snapshot Test hinzufügen?

2025-01-04 15:41 UTC, Fieeesch commented on components/Stage/CoordinateInput.tsx
> +};
schön refactored!

2025-01-04 15:41 UTC, Fieeesch commented on components/Stage/CoordinateInput.tsx
> +  let latitude: string | undefined = undefined;
Warum hier let statt useState?

2025-01-04 15:41 UTC, Fieeesch commented on components/Stage/__tests__/CoordinateInput-test.tsx
> +  it("renders correctly with initial values", () => {
Hier kannst du auch noch einen Snapshot machen

2025-01-04 15:41 UTC, Fieeesch commented on components/Tour/StageMapLine.tsx
> +  circleStrokeColor?: string;
Mag ich

2025-01-04 17:00 UTC, MarcoCoreDuo commented on app/(tabs)/(touren)/createManualStage.tsx
> +  const endDate = useRef(new Date());
useRef ist besser hier finde ich. useState hat oft Dinge neu gerendert, die es gar nicht benötigt haben wie z.B. die Karte. Dadurch hat Diese immer geflackert. Die Komponenten haben dafür einen internen state und bekommen nur initiale Werte übergeben.

2025-01-04 17:04 UTC, MarcoCoreDuo commented
> Mir ist aber ein Bug bei der Synchronisierung der Zeit aufgefallen: Wenn ich die Zeit (egal ob Start oder Ende) im Linken Tab auswähle, wird sie nicht direkt im Button aktualisiert, sondern erst nachdem ich einmal kurz den Tab gewechselt habe. Und wenn ich danach im rechten Tab auf Erstellen klicke, steht da nicht die richtige Uhrzeit. Die Etappe wird dann aber trotzdem mit den gewählten Zeiten erstellt, es ist also nur ein Anzeigefehler. Ich glaube es liegt daran, dass du useRef statt useState verwendest. Bei useState wird nämlich neu gerendert, bei useRef nicht.

Gut, dass dir das aufgefallen ist. Das habe ich tatsächlich übersehen. Ist bei mir jetzt lokal gefixt.

2025-01-04 18:26 UTC, MarcoCoreDuo commented on components/Stage/CoordinateInput.tsx
> +  let latitude: string | undefined = undefined;
Sehr gut, dass du das nochmal gefragt hast. Da muss tatsächlich ein useState hin. Wenn kein value bei der input-Komponente gesetzt ist, aktualisiert sich die Komponente selber, aber wenn der User was eingibt und einmal zur map und dann wieder zurück wechselt, dann kann er nichts mehr eingeben, weil dann value manuel gesetzt wird. So kann ich auch noch verhindern, dass falsche Zeichen eingegeben werden. 👍

2025-01-05 11:04 UTC, Fieeesch requested changes
Der Zeit-Anzeige Bug ist zur hälfte gefixt, aber noch nicht ganz. Hab dir einen Kommentar dazu geschrieben

2025-01-05 13:42 UTC, Fieeesch approved these changes
Okay, jetzt geht alles

2025-01-05 13:42 UTC, merged